### ISSUE TITLE
Code too abstract

### ISSUE THREAD

**Issue by ShikherVerma** [shibhansh/EKF#1]
:stuck_out_tongue:

**Comment by shibhansh** [comment]
It's not anymore :P

**Comment by ShikherVerma** [comment]
I beg to differ. See [EKF/update.cpp](https://github.com/shibhansh/EKF/blob/master/update.cpp)

**Comment by shibhansh** [comment]
Get a life dude :stuck_out_tongue_winking_eye:

**Comment by shibhansh** [comment]
Also baad main ye sab chutiyapa delete ho jata hai na bc
